# Generated by Django 5.2.6 on 2025-10-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_event_attendees_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_extension',
        ),
    ]
