# Generated by Django 5.2.6 on 2025-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='office_location',
            field=models.CharField(blank=True, default='Main Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='position',
            field=models.CharField(blank=True, default='Employee', max_length=100),
        ),
    ]
